---
instances:
- https://medium.com/
routes:
- title: The Airbnb Tech Blog - Medium
  path: https://medium.com/feed/airbnb-engineering
- title: v2ex 最热
  path: https://www.v2ex.com/index.xml
# baseUrl: https://raw.githubusercontent.com/wdssmq/proxy_rsshub/main # The Base Url Of xml folder
