---
instances:
- https://medium.com/
routes:
- title: The Airbnb Tech Blog - Medium
  path: https://medium.com/feed/airbnb-engineering
- title: v2ex 最热
  path: https://www.v2ex.com/index.xml
- title: nyaa [Nemuri]
  path: https://nyaa.si/?page=rss&u=Nemuri
- title: nyaa iDOLM@STER lossless
  path: https://nyaa.si/?page=rss&q=iDOLM%40STER+&c=2_1&f=0
# baseUrl: https://raw.githubusercontent.com/wdssmq/proxy_rsshub/main # The Base Url Of xml folder
