---
instances:
- https://medium.com/
routes:
- title: The Airbnb Tech Blog - Medium
  path: feed/airbnb-engineering
# baseUrl: https://raw.githubusercontent.com/wdssmq/proxy_rsshub/main # The Base Url Of xml folder
